### PR TITLE
prevent invalid enumerator state

### LINKED ISSUE #19: Crash Bug
crash stack:
image

crash code:
image

the log output:
2016-03-16 22:55:04.864 Weiyun[3862:2294084] zone address:0x1042ac000 index:0
2016-03-16 22:55:05.123 Weiyun[3862:2294084] zone address:0x104518000 index:1
2016-03-16 22:55:05.123 Weiyun[3862:2294084] zone address:0x13784a000 index:2
2016-03-16 22:55:05.124 Weiyun[3862:2294084] zone address:0x1047f8000 index:3
2016-03-16 22:55:05.124 Weiyun[3862:2294084] zone address:0x19f939e70 index:4
2016-03-16 22:55:05.124 Weiyun[3862:2294084] zone address:0x137179800 index:5
2016-03-16 22:55:05.130 Weiyun[3862:2294084] zone address:0x1042ac000 index:0
2016-03-16 22:55:05.636 Weiyun[3862:2294084] zone address:0x104518000 index:1
2016-03-16 22:55:05.636 Weiyun[3862:2294084] zone address:0x13784a000 index:2
2016-03-16 22:55:05.637 Weiyun[3862:2294084] zone address:0x1047f8000 index:3
2016-03-16 22:55:05.637 Weiyun[3862:2294084] zone address:0x19f939e70 index:4
Weiyun(3862,0x1a05f9000) malloc: Attempted to register zone more than once: 0x16fd99c18
2016-03-16 22:55:05.637 Weiyun[3862:2294084] zone address:0x137179800 index:5
2016-03-16 22:55:05.637 Weiyun[3862:2294084] zone address:0x16fd99c18 index:6

I don't know what happed, It's crash everytime I want stop record or tap the Heap Bar.

Thanks

### PR DESCRIPTION
**Pull request by haifengkao**
I believe it will close https://github.com/tapwork/HeapInspector-for-iOS/issues/19
Though I don't have extensive tests yet

### CODE REVIEW

**Comment by tapwork** [comment]
sounds reasonable

**Comment by tapwork** [comment]
@haifengkao could you check the latest version 0.4 if it fixes #19

**Comment by haifengkao** [comment]
@tapwork No, the version 0.4 doesn't work at all.

I did a little more research:

Normal Block1


Normal Block2


Corrupted Block


It seems that `EXE_BAD_ACCESS` is a result of an invalid `zone` pointer. If we would verify the content of zone, we can detect if the `zone` object is valid or not.

**Comment by tapwork** [comment]
thanks. looks good

**Comment by tapwork** [comment]
@haifengkao right

**Pull request merged**
